from typing import BinaryIO


def decode(data: bytes) -> bytes: ...


def decode_file(input: BinaryIO, output: BinaryIO, buf_rate: int = 10) -> None: ...


def encode(data: bytes) -> bytes: ...


def encode_file(input: BinaryIO, output: BinaryIO, boolwrite_head: bool = False, buf_rate: int = 10) -> None: ...
